[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

# Proxy all /api/* requests to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
